<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdvertisementSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('advertisements')->insert([
            [
                'id'                   => 1,
                'views_count'          => 567,
                'unique_views_count'   => 456,
                'user_id'              => 2,
                'listing_package_id'   => 3,
                'listing_days'         => 30,
                'advertisable_type'    => 'App\\Models\\House',
                'advertisable_id'      => 1,
                'title'                => 'Premium Villa in Kacyiru — Own Your Dream Home Today',
                'description'          => 'Don\'t miss this stunning 4-bedroom villa in Kacyiru with panoramic Kigali views. Italian marble finishes, smart home system, and landscaped garden. Contact agent Marie-Claire Uwimana for a private viewing. MoMo payment accepted for earnest deposit.',
                'contact_phone'        => '+250788234567',
                'contact_email'        => 'marieclaire@terra.rw',
                'location'             => 'Kacyiru, Gasabo, Kigali',
                'price_amount'         => 85000000.00,
                'currency'             => 'RWF',
                'images'               => json_encode(['ads/kacyiru-villa-ad-1.jpg', 'ads/kacyiru-villa-ad-2.jpg']),
                'video_path'           => 'ads/kacyiru-villa-promo.mp4',
                'payment_status'       => 'confirmed',
                'momo_phone'           => '+250788234567',
                'momo_transaction_id'  => 'MTN20260715001',
                'payment_submitted_at' => now()->subDays(15),
                'payment_confirmed_at' => now()->subDays(14),
                'payment_confirmed_by' => 1,
                'status'               => 'active',
                'starts_at'            => now()->subDays(14),
                'expires_at'           => now()->addDays(16),
                'impressions'          => 2345,
                'clicks'               => 178,
                'admin_notes'          => null,
                'created_at'           => now()->subDays(15),
                'updated_at'           => now(),
            ],
            [
                'id'                   => 2,
                'views_count'          => 345,
                'unique_views_count'   => 289,
                'user_id'              => 5,
                'listing_package_id'   => 2,
                'listing_days'         => 14,
                'advertisable_type'    => 'App\\Models\\Land',
                'advertisable_id'      => 1,
                'title'                => 'Prime Plot in Nyagatovu — Fast-Developing Area, 15 Min from CBD',
                'description'          => 'Invest in this 600 sqm residential plot in Nyagatovu, Kimironko. Flat terrain, R1 zoning, all utilities connected. Title deed verified. Price negotiable for serious buyers. Contact agent Eric Niyonzima for site visit.',
                'contact_phone'        => '+250788567890',
                'contact_email'        => 'eric@terra.rw',
                'location'             => 'Nyagatovu, Kimironko, Gasabo',
                'price_amount'         => 25000000.00,
                'currency'             => 'RWF',
                'images'               => json_encode(['ads/nyagatovu-plot-ad-1.jpg']),
                'video_path'           => null,
                'payment_status'       => 'confirmed',
                'momo_phone'           => '+250788567890',
                'momo_transaction_id'  => 'MTN20260720002',
                'payment_submitted_at' => now()->subDays(10),
                'payment_confirmed_at' => now()->subDays(9),
                'payment_confirmed_by' => 1,
                'status'               => 'active',
                'starts_at'            => now()->subDays(9),
                'expires_at'           => now()->addDays(5),
                'impressions'          => 1234,
                'clicks'               => 89,
                'admin_notes'          => null,
                'created_at'           => now()->subDays(10),
                'updated_at'           => now(),
            ],
            [
                'id'                   => 3,
                'views_count'          => 234,
                'unique_views_count'   => 198,
                'user_id'              => 2,
                'listing_package_id'   => 4,
                'listing_days'         => 7,
                'advertisable_type'    => 'App\\Models\\House',
                'advertisable_id'      => 2,
                'title'                => 'URGENT: Family Home in Nyamirambo — Reduced Price, Must Sell!',
                'description'          => 'Urgent sale! Beautiful 3-bedroom bungalow in Nyamirambo. Recently renovated with new roof and modern kitchen. Price reduced from 40M to 35M RWF. All documents ready. Contact Marie-Claire immediately for viewing.',
                'contact_phone'        => '+250788234567',
                'contact_email'        => 'marieclaire@terra.rw',
                'location'             => 'Nyamirambo, Nyarugenge, Kigali',
                'price_amount'         => 35000000.00,
                'currency'             => 'RWF',
                'images'               => json_encode(['ads/nyamirambo-urgent-ad-1.jpg', 'ads/nyamirambo-urgent-ad-2.jpg']),
                'video_path'           => null,
                'payment_status'       => 'confirmed',
                'momo_phone'           => '+250788234567',
                'momo_transaction_id'  => 'MTN20260725003',
                'payment_submitted_at' => now()->subDays(5),
                'payment_confirmed_at' => now()->subDays(4),
                'payment_confirmed_by' => 1,
                'status'               => 'active',
                'starts_at'            => now()->subDays(4),
                'expires_at'           => now()->addDays(3),
                'impressions'          => 890,
                'clicks'               => 67,
                'admin_notes'          => 'Urgent sale package — approved for priority placement.',
                'created_at'           => now()->subDays(5),
                'updated_at'           => now(),
            ],
            [
                'id'                   => 4,
                'views_count'          => 123,
                'unique_views_count'   => 98,
                'user_id'              => 4,
                'listing_package_id'   => 1,
                'listing_days'         => 7,
                'advertisable_type'    => 'App\\Models\\Land',
                'advertisable_id'      => 5,
                'title'                => 'Investment Plot Near Bugesera Airport — R2 Zoning',
                'description'          => '900 sqm plot just 5 km from the new Bugesera International Airport. R2 zoning allows for multi-family development. Strategic investment opportunity as the area rapidly develops. Contact Diane for more details.',
                'contact_phone'        => '+250788456789',
                'contact_email'        => 'diane@terra.rw',
                'location'             => 'Nyamata, Bugesera, Eastern Province',
                'price_amount'         => 12000000.00,
                'currency'             => 'RWF',
                'images'               => json_encode(['ads/bugesera-plot-ad-1.jpg']),
                'video_path'           => null,
                'payment_status'       => 'pending',
                'momo_phone'           => '+250788456789',
                'momo_transaction_id'  => null,
                'payment_submitted_at' => null,
                'payment_confirmed_at' => null,
                'payment_confirmed_by' => null,
                'status'               => 'pending_review',
                'starts_at'            => null,
                'expires_at'           => null,
                'impressions'          => 0,
                'clicks'               => 0,
                'admin_notes'          => null,
                'created_at'           => now(),
                'updated_at'           => now(),
            ],
            [
                'id'                   => 5,
                'views_count'          => 0,
                'unique_views_count'   => 0,
                'user_id'              => 2,
                'listing_package_id'   => 5,
                'listing_days'         => 60,
                'advertisable_type'    => 'App\\Models\\House',
                'advertisable_id'      => 5,
                'title'                => 'Urwego Development — New 5-Bedroom Homes in Kicukiro',
                'description'          => 'Urwego Development Corporation presents brand new 5-bedroom double storey homes in Biryogo, Kicukiro. Premium materials, modern design, and spacious layout. Pre-construction pricing available. Contact us for a developer walkthrough.',
                'contact_phone'        => '+250788444555',
                'contact_email'        => 'info@urwego.rw',
                'location'             => 'Biryogo, Kicukiro, Kigali',
                'price_amount'         => 65000000.00,
                'currency'             => 'RWF',
                'images'               => json_encode(['ads/urwego-biryogo-ad-1.jpg', 'ads/urwego-biryogo-ad-2.jpg', 'ads/urwego-biryogo-ad-3.jpg']),
                'video_path'           => 'ads/urwego-biryogo-promo.mp4',
                'payment_status'       => 'pending',
                'momo_phone'           => '+250788444555',
                'momo_transaction_id'  => null,
                'payment_submitted_at' => null,
                'payment_confirmed_at' => null,
                'payment_confirmed_by' => null,
                'status'               => 'draft',
                'starts_at'            => null,
                'expires_at'           => null,
                'impressions'          => 0,
                'clicks'               => 0,
                'admin_notes'          => null,
                'created_at'           => now(),
                'updated_at'           => now(),
            ],
        ]);
    }
}