<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AgentsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('agents')->insert([
            [
                'id'                     => 1,
                'views_count'            => 342,
                'unique_views_count'     => 287,
                'agent_level_id'         => 3, // Gold
                'total_referrals'        => 12,
                'total_revenue_generated'=> 28500000.00,
                'user_id'                => 2,
                'full_name'              => 'Marie-Claire Uwimana',
                'email'                  => 'marieclaire@terra.rw',
                'phone'                  => '+250788234567',
                'bio'                    => 'Top-rated real estate agent in Kigali with over 8 years of experience in residential and commercial property sales. Specializes in Gasabo and Nyarugenge districts with deep knowledge of the Kigali property market.',
                'linkedin'               => 'https://linkedin.com/in/marieclaire-uwimana',
                'facebook'               => 'https://facebook.com/marieclaire.terra',
                'instagram'              => 'https://instagram.com/marieclaire_terra_rw',
                'twitter'                => 'https://twitter.com/mc_uwimana',
                'profile_image'          => 'agents/marie-claire-uwimana.jpg',
                'whatsapp'               => '+250788234567',
                'office_location'        => 'KG 11 Ave, Kacyiru, Gasabo, Kigali',
                'languages'              => 'Kinyarwanda, English, French',
                'is_verified'            => 1,
                'province'               => 'Kigali City',
                'district'               => 'Gasabo',
                'sector'                 => 'Kacyiru',
                'status'                 => 'Active',
                'created_at'             => now(),
                'updated_at'             => now(),
            ],
            [
                'id'                     => 2,
                'views_count'            => 198,
                'unique_views_count'     => 165,
                'agent_level_id'         => 2, // Silver
                'total_referrals'        => 7,
                'total_revenue_generated'=> 15200000.00,
                'user_id'                => 5,
                'full_name'              => 'Eric Niyonzima',
                'email'                  => 'eric@terra.rw',
                'phone'                  => '+250788567890',
                'bio'                    => 'Passionate real estate agent focusing on land sales in Kigali and the Eastern Province. Known for honest dealings and transparent pricing with verified UPI documentation.',
                'linkedin'               => 'https://linkedin.com/in/eric-niyonzima',
                'facebook'               => null,
                'instagram'              => 'https://instagram.com/eric_niyonzima_realty',
                'twitter'                => null,
                'profile_image'          => 'agents/eric-niyonzima.jpg',
                'whatsapp'               => '+250788567890',
                'office_location'        => 'KN 3 Rd, Nyarugenge, Kigali',
                'languages'              => 'Kinyarwanda, English, Swahili',
                'is_verified'            => 1,
                'province'               => 'Kigali City',
                'district'               => 'Nyarugenge',
                'sector'                 => 'Nyarugenge',
                'status'                 => 'Active',
                'created_at'             => now(),
                'updated_at'             => now(),
            ],
            [
                'id'                     => 3,
                'views_count'            => 87,
                'unique_views_count'     => 72,
                'agent_level_id'         => 1, // Bronze
                'total_referrals'        => 2,
                'total_revenue_generated'=> 4500000.00,
                'user_id'                => null,
                'full_name'              => 'Clarisse Mugabekazi',
                'email'                  => 'clarisse.m@terra.rw',
                'phone'                  => '+250788678901',
                'bio'                    => 'Newly certified agent specializing in the Northern Province, particularly Musanze and Burera. Offers personalized service for first-time home buyers in the land of a thousand hills.',
                'linkedin'               => null,
                'facebook'               => 'https://facebook.com/clarisse.mugabekazi',
                'instagram'              => null,
                'twitter'                => null,
                'profile_image'          => 'agents/clarisse-mugabekazi.jpg',
                'whatsapp'               => '+250788678901',
                'office_location'        => 'Musanze Town, Northern Province',
                'languages'              => 'Kinyarwanda, English, French',
                'is_verified'            => 0,
                'province'               => 'Northern Province',
                'district'               => 'Musanze',
                'sector'                 => 'Musanze',
                'status'                 => 'Pending Approval',
                'created_at'             => now(),
                'updated_at'             => now(),
            ],
            [
                'id'                     => 4,
                'views_count'            => 456,
                'unique_views_count'     => 389,
                'agent_level_id'         => 4, // Platinum
                'total_referrals'        => 24,
                'total_revenue_generated'=> 65000000.00,
                'user_id'                => null,
                'full_name'              => 'Robert Bizimana',
                'email'                  => 'robert.b@terra.rw',
                'phone'                  => '+250788789012',
                'bio'                    => 'Veteran real estate agent with 15+ years in the Rwandan property market. Former RHA board member. Specializes in luxury properties in Kigali and commercial investments nationwide.',
                'linkedin'               => 'https://linkedin.com/in/robert-bizimana',
                'facebook'               => 'https://facebook.com/robert.bizimana.realty',
                'instagram'              => 'https://instagram.com/robert_bizimana_luxury',
                'twitter'                => 'https://twitter.com/rbizimana',
                'profile_image'          => 'agents/robert-bizimana.jpg',
                'whatsapp'               => '+250788789012',
                'office_location'        => 'KG 9 Ave, Kimihurura, Gasabo, Kigali',
                'languages'              => 'Kinyarwanda, English, French, Swahili',
                'is_verified'            => 1,
                'province'               => 'Kigali City',
                'district'               => 'Gasabo',
                'sector'                 => 'Kimihurura',
                'status'                 => 'Active',
                'created_at'             => now(),
                'updated_at'             => now(),
            ],
            [
                'id'                     => 5,
                'views_count'            => 134,
                'unique_views_count'     => 112,
                'agent_level_id'         => 2, // Silver
                'total_referrals'        => 5,
                'total_revenue_generated'=> 9800000.00,
                'user_id'                => null,
                'full_name'              => 'Anitha Uwituze',
                'email'                  => 'anitha.u@terra.rw',
                'phone'                  => '+250788890123',
                'bio'                    => 'Dedicated agent covering the Western Province, with expertise in Rubavu and Rusizi lakefront properties. Helps diaspora clients find investment properties back home in Rwanda.',
                'linkedin'               => 'https://linkedin.com/in/anitha-uwituze',
                'facebook'               => 'https://facebook.com/anitha.uwituze.realty',
                'instagram'              => null,
                'twitter'                => null,
                'profile_image'          => 'agents/anitha-uwituze.jpg',
                'whatsapp'               => '+250788890123',
                'office_location'        => 'Rubavu Town, Western Province',
                'languages'              => 'Kinyarwanda, English, French',
                'is_verified'            => 1,
                'province'               => 'Western Province',
                'district'               => 'Rubavu',
                'sector'                 => 'Gisenyi',
                'status'                 => 'Active',
                'created_at'             => now(),
                'updated_at'             => now(),
            ],
        ]);
    }
}