<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArchitecturalDesignSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('architectural_designs')->insert([
            [
                'id'                         => 1,
                'views_count'                => 456,
                'unique_views_count'         => 378,
                'title'                      => '3-Bedroom Modern Bungalow — Kigali Style',
                'slug'                       => '3-bedroom-modern-bungalow-kigali-style',
                'user_id'                    => 3,
                'agent_id'                   => 1,
                'added_by'                   => 3,
                'listing_package_id'         => 5,
                'listing_days'               => 30,
                'listing_fee_total'          => 9000.00,
                'agent_listing_commission'   => 1350.00,
                'terra_listing_revenue'      => 7650.00,
                'owner_name'                 => 'Arch. Grace Iribagiza',
                'owner_email'                => 'grace.i@terra.rw',
                'owner_phone'                => '+250788567002',
                'owner_id_number'           => null,
                'category_id'                => 1,
                'service_id'                 => 5,
                'description'                => 'Contemporary 3-bedroom bungalow design optimized for Kigali hillside terrain. Features open-plan living and dining, master en-suite, covered parking, and a veranda with city views. Compliant with Rwanda Building Code and Kigali City One-Stop Center submission requirements. Includes floor plans, elevations, sections, and 3D renders.',
                'design_file'                => 'designs/3bed-bungalow-kigali-style.zip',
                'preview_image'              => 'designs/previews/3bed-bungalow-preview.jpg',
                'price'                      => 150000.00,
                'is_free'                    => 0,
                'status'                     => 'approved',
                'featured'                   => 1,
                'download_count'             => 67,
                'is_approved'                => 1,
                'video_url'                  => 'https://youtube.com/watch?v=3bed-bungalow-3d',
                'currency'                   => 'RWF',
                'created_at'                 => now(),
                'updated_at'                 => now(),
            ],
            [
                'id'                         => 2,
                'views_count'                => 312,
                'unique_views_count'         => 256,
                'title'                      => '4-Bedroom Double Storey — Premium Family Home',
                'slug'                       => '4-bedroom-double-storey-premium-family',
                'user_id'                    => 3,
                'agent_id'                   => null,
                'added_by'                   => 3,
                'listing_package_id'         => 5,
                'listing_days'               => 30,
                'listing_fee_total'          => 9000.00,
                'agent_listing_commission'   => 0.00,
                'terra_listing_revenue'      => 9000.00,
                'owner_name'                 => 'Arch. Grace Iribagiza',
                'owner_email'                => 'grace.i@terra.rw',
                'owner_phone'                => '+250788567002',
                'owner_id_number'           => null,
                'category_id'                => 2,
                'service_id'                 => 5,
                'description'                => 'Elegant 4-bedroom double storey design with a separate family room, study, and domestic quarter. Designed for R1 and R2 zoned plots in Kigali. Includes ground floor, first floor, roof plan, 4 elevations, and detailed structural drawings. RBC compliant with earthquake resistance standards.',
                'design_file'                => 'designs/4bed-double-storey-premium.zip',
                'preview_image'              => 'designs/previews/4bed-double-storey-preview.jpg',
                'price'                      => 250000.00,
                'is_free'                    => 0,
                'status'                     => 'approved',
                'featured'                   => 0,
                'download_count'             => 34,
                'is_approved'                => 1,
                'video_url'                  => null,
                'currency'                   => 'RWF',
                'created_at'                 => now(),
                'updated_at'                 => now(),
            ],
            [
                'id'                         => 3,
                'views_count'                => 789,
                'unique_views_count'         => 623,
                'title'                      => 'Free Starter House Plan — 2-Bedroom Bungalow',
                'slug'                       => 'free-starter-2-bedroom-bungalow',
                'user_id'                    => 1,
                'agent_id'                   => null,
                'added_by'                   => 1,
                'listing_package_id'         => 5,
                'listing_days'               => 30,
                'listing_fee_total'          => 9000.00,
                'agent_listing_commission'   => 0.00,
                'terra_listing_revenue'      => 9000.00,
                'owner_name'                 => 'Terra Rwanda',
                'owner_email'                => 'info@terra.rw',
                'owner_phone'                => '+250788000000',
                'owner_id_number'           => null,
                'category_id'                => 1,
                'service_id'                 => 5,
                'description'                => 'Free starter house plan designed for first-time homeowners in Rwanda. Simple 2-bedroom bungalow layout with basic amenities. Perfect for R1 residential plots. Includes floor plan, 2 elevations, and a basic 3D sketch. Ideal for budget-conscious builders in rural and peri-urban areas.',
                'design_file'                => 'designs/free-2bed-bungalow-starter.zip',
                'preview_image'              => 'designs/previews/free-2bed-starter-preview.jpg',
                'price'                      => 0.00,
                'is_free'                    => 1,
                'status'                     => 'approved',
                'featured'                   => 1,
                'download_count'             => 234,
                'is_approved'                => 1,
                'video_url'                  => null,
                'currency'                   => 'RWF',
                'created_at'                 => now(),
                'updated_at'                 => now(),
            ],
            [
                'id'                         => 4,
                'views_count'                => 198,
                'unique_views_count'         => 167,
                'title'                      => 'Commercial Retail Space — Single-Storey Shop Design',
                'slug'                       => 'commercial-retail-single-storey-shop',
                'user_id'                    => 3,
                'agent_id'                   => 4,
                'added_by'                   => 3,
                'listing_package_id'         => 5,
                'listing_days'               => 30,
                'listing_fee_total'          => 9000.00,
                'agent_listing_commission'   => 1350.00,
                'terra_listing_revenue'      => 7650.00,
                'owner_name'                 => 'Arch. Grace Iribagiza',
                'owner_email'                => 'grace.i@terra.rw',
                'owner_phone'                => '+250788567002',
                'owner_id_number'           => null,
                'category_id'                => 3,
                'service_id'                 => 5,
                'description'                => 'Professional single-storey commercial retail design suitable for shops, pharmacies, and offices. Compliant with commercial zoning requirements in Kigali and secondary cities. Features a showroom area, back office, storage, and customer parking. Includes fire safety provisions per RBC standards.',
                'design_file'                => 'designs/commercial-retail-shop.zip',
                'preview_image'              => 'designs/previews/commercial-retail-preview.jpg',
                'price'                      => 200000.00,
                'is_free'                    => 0,
                'status'                     => 'approved',
                'featured'                   => 0,
                'download_count'             => 12,
                'is_approved'                => 1,
                'video_url'                  => null,
                'currency'                   => 'RWF',
                'created_at'                 => now(),
                'updated_at'                 => now(),
            ],
            [
                'id'                         => 5,
                'views_count'                => 267,
                'unique_views_count'         => 223,
                'title'                      => '6-Unit Apartment Block Design — Kigali R2 Zoning',
                'slug'                       => '6-unit-apartment-block-kigali-r2',
                'user_id'                    => 3,
                'agent_id'                   => null,
                'added_by'                   => 3,
                'listing_package_id'         => 5,
                'listing_days'               => 30,
                'listing_fee_total'          => 9000.00,
                'agent_listing_commission'   => 0.00,
                'terra_listing_revenue'      => 9000.00,
                'owner_name'                 => 'Arch. Grace Iribagiza',
                'owner_email'                => 'grace.i@terra.rw',
                'owner_phone'                => '+250788567002',
                'owner_id_number'           => null,
                'category_id'                => 4,
                'service_id'                 => 5,
                'description'                => 'Modern 6-unit apartment block design for R2 zoned plots. Each unit features 2 bedrooms, open kitchen, living room, and bathroom. Includes ground floor parking, shared laundry area, and a rooftop terrace. Compliant with Kigali City master plan density requirements. Full structural and MEP drawings included.',
                'design_file'                => 'designs/6unit-apartment-block-r2.zip',
                'preview_image'              => 'designs/previews/6unit-apartment-preview.jpg',
                'price'                      => 400000.00,
                'is_free'                    => 0,
                'status'                     => 'approved',
                'featured'                   => 0,
                'download_count'             => 28,
                'is_approved'                => 1,
                'video_url'                  => 'https://youtube.com/watch?v=6unit-apartment-3d',
                'currency'                   => 'RWF',
                'created_at'                 => now(),
                'updated_at'                 => now(),
            ],
        ]);
    }
}