<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HouseSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('houses')->insert([
            [
                'id'                        => 1,
                'views_count'               => 512,
                'unique_views_count'        => 423,
                'user_id'                   => 2,
                'agent_id'                  => 1,
                'added_by'                  => 2,
                'listing_package_id'        => 2,
                'listing_days'              => 60,
                'listing_fee_total'         => 60000.00,
                'agent_listing_commission'  => 12000.00,
                'terra_listing_revenue'     => 48000.00,
                'owner_name'                => 'Jean-Bosco Niyonsaba',
                'owner_email'               => 'jbosco@gmail.com',
                'owner_phone'               => '+250788111222',
                'owner_id_number'           => '1199780001234567',
                'title'                     => 'Modern 4-Bedroom Villa in Kacyiru with Panoramic Kigali View',
                'upi'                       => '1/02/03/004/012',
                'type'                      => 'Villa',
                'price'                     => 85000000.00,
                'area_sqft'                 => 3200,
                'status'                    => 'available',
                'negotiable'                => 'negotiable',
                'condition'                 => 'for_sale',
                'bedrooms'                  => 4,
                'bathrooms'                 => 3,
                'garages'                   => 2,
                'description'               => 'Stunning modern villa located in the prestigious Kacyiru neighborhood with breathtaking views of Kigali skyline. Features include open-plan living area, Italian marble finishes, smart home system, landscaped garden with outdoor entertainment area, and 24/7 security. Walking distance to ministries and international organizations. All documents verified with RLMUA.',
                'province'                  => 'Kigali City',
                'district'                  => 'Gasabo',
                'sector'                    => 'Kacyiru',
                'cell'                      => 'Kacyiru',
                'village'                   => 'Urugwiro',
                'is_approved'               => 1,
                'video_url'                 => 'https://youtube.com/watch?v=kacyiru-villa-terra',
                'latitude'                  => -1.9440700,
                'longitude'                 => 30.0618800,
                'currency'                  => 'RWF',
                'client_id'                 => 1,
                'service_id'                => 1,
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 2,
                'views_count'               => 387,
                'unique_views_count'        => 312,
                'user_id'                   => 5,
                'agent_id'                  => 2,
                'added_by'                  => 5,
                'listing_package_id'        => 1,
                'listing_days'              => 30,
                'listing_fee_total'         => 15000.00,
                'agent_listing_commission'  => 2250.00,
                'terra_listing_revenue'     => 12750.00,
                'owner_name'                => 'Félicité Mukandayisenga',
                'owner_email'               => 'felicite.m@gmail.com',
                'owner_phone'               => '+250788999000',
                'owner_id_number'           => '1199820008901234',
                'title'                     => '3-Bedroom Bungalow in Nyamirambo — Ideal Family Home',
                'upi'                       => '1/01/01/002/008',
                'type'                      => 'Bungalow',
                'price'                     => 35000000.00,
                'area_sqft'                 => 1800,
                'status'                    => 'available',
                'negotiable'                => 'negotiable',
                'condition'                 => 'for_sale',
                'bedrooms'                  => 3,
                'bathrooms'                 => 2,
                'garages'                   => 1,
                'description'               => 'Well-maintained 3-bedroom bungalow in the vibrant Nyamirambo area. Recently renovated with new roofing, tiled floors, and modern kitchen. Includes a perimeter wall, paved parking, and a small garden. Close to Nyamirambo market and public transport. Title deed available and verified.',
                'province'                  => 'Kigali City',
                'district'                  => 'Nyarugenge',
                'sector'                    => 'Nyarugenge',
                'cell'                      => 'Nyamirambo',
                'village'                   => 'Kabusunzu',
                'is_approved'               => 1,
                'video_url'                 => null,
                'latitude'                  => -1.9574000,
                'longitude'                 => 30.0488000,
                'currency'                  => 'RWF',
                'client_id'                 => null,
                'service_id'                => 1,
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 3,
                'views_count'               => 234,
                'unique_views_count'        => 198,
                'user_id'                   => 2,
                'agent_id'                  => 4,
                'added_by'                  => 2,
                'listing_package_id'        => 2,
                'listing_days'              => 60,
                'listing_fee_total'         => 60000.00,
                'agent_listing_commission'  => 12000.00,
                'terra_listing_revenue'     => 48000.00,
                'owner_name'                => 'Chantal Mukamana',
                'owner_email'               => 'chantal.m@gmail.com',
                'owner_phone'               => '+250788222333',
                'owner_id_number'           => null,
                'title'                     => 'Luxury Penthouse Apartment at Kimihurura Heights',
                'upi'                       => '1/02/05/001/003',
                'type'                      => 'Apartment',
                'price'                     => 120000000.00,
                'area_sqft'                 => 2800,
                'status'                    => 'available',
                'negotiable'                => 'non_negotiable',
                'condition'                 => 'for_sale',
                'bedrooms'                  => 3,
                'bathrooms'                 => 2,
                'garages'                   => 2,
                'description'               => 'Exclusive penthouse apartment in the prestigious Kimihurura area with floor-to-ceiling windows offering stunning views of the Kigali Convention Centre and the city skyline. Premium finishes throughout, imported kitchen, built-in wardrobes, and a private rooftop terrace. Building features include gym, swimming pool, and 24/7 security with CCTV.',
                'province'                  => 'Kigali City',
                'district'                  => 'Gasabo',
                'sector'                    => 'Remera',
                'cell'                      => 'Kimihurura',
                'village'                   => 'Kamate',
                'is_approved'               => 1,
                'video_url'                 => 'https://youtube.com/watch?v=kimihurura-penthouse',
                'latitude'                  => -1.9355000,
                'longitude'                 => 30.0885000,
                'currency'                  => 'RWF',
                'client_id'                 => 2,
                'service_id'                => 1,
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 4,
                'views_count'               => 178,
                'unique_views_count'        => 145,
                'user_id'                   => 4,
                'agent_id'                  => 3,
                'added_by'                  => 4,
                'listing_package_id'        => 1,
                'listing_days'              => 30,
                'listing_fee_total'         => 15000.00,
                'agent_listing_commission'  => 2250.00,
                'terra_listing_revenue'     => 12750.00,
                'owner_name'                => 'Diane Ishimwe',
                'owner_email'               => 'diane@terra.rw',
                'owner_phone'               => '+250788456789',
                'owner_id_number'           => '1199900004567890',
                'title'                     => 'Cozy 2-Bedroom House for Rent in Musanze — Near Volcanoes National Park',
                'upi'                       => '2/04/07/003/011',
                'type'                      => 'House',
                'price'                     => 250000.00,
                'area_sqft'                 => 1200,
                'status'                    => 'available',
                'negotiable'                => 'negotiable',
                'condition'                 => 'for_rent',
                'bedrooms'                  => 2,
                'bathrooms'                 => 1,
                'garages'                   => 0,
                'description'               => 'Charming 2-bedroom house available for rent in Musanze town, just 30 minutes from Volcanoes National Park. Perfect for tourism professionals or nature lovers. Features a cozy living room, equipped kitchen, and a small garden with mountain views. Quiet neighborhood with reliable water and electricity.',
                'province'                  => 'Northern Province',
                'district'                  => 'Musanze',
                'sector'                    => 'Musanze',
                'cell'                      => 'Ruhengeri',
                'village'                   => 'Cyabararika',
                'is_approved'               => 1,
                'video_url'                 => null,
                'latitude'                  => -1.4985000,
                'longitude'                 => 29.6350000,
                'currency'                  => 'RWF',
                'client_id'                 => null,
                'service_id'                => 1,
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 5,
                'views_count'               => 301,
                'unique_views_count'        => 256,
                'user_id'                   => 2,
                'agent_id'                  => 5,
                'added_by'                  => 2,
                'listing_package_id'        => 2,
                'listing_days'              => 60,
                'listing_fee_total'         => 60000.00,
                'agent_listing_commission'  => 12000.00,
                'terra_listing_revenue'     => 48000.00,
                'owner_name'                => 'Urwego Development Corporation',
                'owner_email'               => 'info@urwego.rw',
                'owner_phone'               => '+250788444555',
                'owner_id_number'           => null,
                'title'                     => 'New 5-Bedroom Double Storey in Biryogo — Kicukiro New Development',
                'upi'                       => '1/03/06/005/002',
                'type'                      => 'Double Storey',
                'price'                     => 65000000.00,
                'area_sqft'                 => 3600,
                'status'                    => 'available',
                'negotiable'                => 'negotiable',
                'condition'                 => 'for_sale',
                'bedrooms'                  => 5,
                'bathrooms'                 => 4,
                'garages'                   => 2,
                'description'               => 'Brand new 5-bedroom double storey home in the rapidly developing Biryogo area of Kicukiro. Built by Urwego Development Corporation with premium materials. Features include spacious rooms, en-suite master bedroom, modern kitchen with granite countertops, and a large backyard. Near Kicukiro main road and upcoming commercial centers.',
                'province'                  => 'Kigali City',
                'district'                  => 'Kicukiro',
                'sector'                    => 'Kicukiro',
                'cell'                      => 'Gatenga',
                'village'                   => 'Biryogo',
                'is_approved'               => 1,
                'video_url'                 => 'https://youtube.com/watch?v=biryogo-double-storey',
                'latitude'                  => -1.9670000,
                'longitude'                 => 30.1030000,
                'currency'                  => 'RWF',
                'client_id'                 => 4,
                'service_id'                => 1,
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
        ]);
    }
}