<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JobListingSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('job_listings')->insert([
            [
                'id'                     => 1,
                'company_name'           => 'Terra Rwanda Ltd',
                'company_email'          => 'careers@terra.rw',
                'company_phone'          => '+250788000000',
                'company_logo'           => 'companies/terra-rwanda-logo.png',
                'company_website'        => 'https://www.terra.rw',
                'title'                  => 'Senior Laravel Developer — Real Estate Platform',
                'slug'                   => 'senior-laravel-developer-terra-rwanda',
                'description'            => 'We are looking for a Senior Laravel Developer to join our growing team and help build the next generation of Terra Rwanda\'s property exchange platform. You will work on payment integration (MoMo/Airtel), agent commission systems, and property listing management.',
                'requirements'           => '5+ years PHP/Laravel experience, experience with payment gateways, knowledge of Rwanda land administration systems, fluent in English and Kinyarwanda.',
                'benefits'               => 'Competitive salary, health insurance, flexible remote work, annual bonus, professional development budget.',
                'location'               => 'Kigali, Rwanda (Hybrid)',
                'job_type'               => 'full-time',
                'category'               => 'Software Development',
                'salary_min'             => 2500000,
                'salary_max'             => 4000000,
                'salary_currency'        => 'RWF',
                'show_salary'            => 1,
                'application_deadline'   => '2026-08-31',
                'application_email'      => 'careers@terra.rw',
                'application_url'        => null,
                'listing_package_id'     => 2,
                'days_purchased'         => 60,
                'views_count'            => 567,
                'unique_views_count'     => 456,
                'total_amount'           => 60000,
                'agent_commission_amount'=> 12000,
                'terra_share_amount'     => 48000,
                'payment_status'         => 'paid',
                'payment_reference'      => 'MTN20260701001',
                'payment_method'         => 'momo',
                'paid_at'                => now()->subDays(29),
                'status'                 => 'active',
                'published_at'           => now()->subDays(29),
                'expires_at'             => now()->addDays(31),
                'rejection_reason'       => null,
                'user_id'                => 1,
                'created_at'             => now()->subDays(30),
                'updated_at'             => now(),
            ],
            [
                'id'                     => 2,
                'company_name'           => 'Urwego Development Corporation',
                'company_email'          => 'hr@urwego.rw',
                'company_phone'          => '+250788444555',
                'company_logo'           => 'companies/urwego-logo.png',
                'company_website'        => 'https://www.urwego.rw',
                'title'                  => 'Real Estate Sales Manager — Kigali Region',
                'slug'                   => 'real-estate-sales-manager-urwego',
                'description'            => 'Urwego Development Corporation is hiring a Sales Manager to lead our residential property sales team in Kigali. The ideal candidate will manage a team of 8-10 agents, drive sales targets, and build relationships with property investors.',
                'requirements'           => '7+ years real estate experience in Rwanda, proven sales track record, RHA certification preferred, strong network in Kigali property market.',
                'benefits'               => 'Base salary + commission, company vehicle, health insurance, annual retreat.',
                'location'               => 'Kigali, Rwanda',
                'job_type'               => 'full-time',
                'category'               => 'Real Estate',
                'salary_min'             => 1500000,
                'salary_max'             => 2500000,
                'salary_currency'        => 'RWF',
                'show_salary'            => 1,
                'application_deadline'   => '2026-08-15',
                'application_email'      => 'hr@urwego.rw',
                'application_url'        => null,
                'listing_package_id'     => 2,
                'days_purchased'         => 60,
                'views_count'            => 345,
                'unique_views_count'     => 289,
                'total_amount'           => 60000,
                'agent_commission_amount'=> 12000,
                'terra_share_amount'     => 48000,
                'payment_status'         => 'paid',
                'payment_reference'      => 'MTN20260705002',
                'payment_method'         => 'momo',
                'paid_at'                => now()->subDays(24),
                'status'                 => 'active',
                'published_at'           => now()->subDays(24),
                'expires_at'             => now()->addDays(36),
                'rejection_reason'       => null,
                'user_id'                => 2,
                'created_at'             => now()->subDays(25),
                'updated_at'             => now(),
            ],
            [
                'id'                     => 3,
                'company_name'           => 'Rwanda Land Management & Use Authority',
                'company_email'          => 'recruitment@rlmua.gov.rw',
                'company_phone'          => '+250788700000',
                'company_logo'           => 'companies/rlmua-logo.png',
                'company_website'        => 'https://www.rlmua.gov.rw',
                'title'                  => 'Cadastral Surveyor — Southern Province',
                'slug'                   => 'cadastral-surveyor-rlmua-southern',
                'description'            => 'RLMUA is seeking a qualified Cadastral Surveyor to support land registration activities in the Southern Province. The role involves field surveys, UPI assignment, boundary demarcation, and quality assurance of survey data.',
                'requirements'           => 'Degree in Geomatics or Land Surveying, 3+ years cadastral experience, proficiency with GPS/GNSS equipment, knowledge of Rwanda land law.',
                'benefits'               => 'Government salary scale, pension, health insurance, field allowances.',
                'location'               => 'Huye, Southern Province, Rwanda',
                'job_type'               => 'full-time',
                'category'               => 'Land Surveying',
                'salary_min'             => 800000,
                'salary_max'             => 1200000,
                'salary_currency'        => 'RWF',
                'show_salary'            => 1,
                'application_deadline'   => '2026-09-15',
                'application_email'      => 'recruitment@rlmua.gov.rw',
                'application_url'        => 'https://www.rlmua.gov.rw/careers',
                'listing_package_id'     => 1,
                'days_purchased'         => 30,
                'views_count'            => 234,
                'unique_views_count'     => 198,
                'total_amount'           => 15000,
                'agent_commission_amount'=> 2250,
                'terra_share_amount'     => 12750,
                'payment_status'         => 'paid',
                'payment_reference'      => 'MTN20260710003',
                'payment_method'         => 'momo',
                'paid_at'                => now()->subDays(19),
                'status'                 => 'active',
                'published_at'           => now()->subDays(19),
                'expires_at'             => now()->addDays(11),
                'rejection_reason'       => null,
                'user_id'                => 1,
                'created_at'             => now()->subDays(20),
                'updated_at'             => now(),
            ],
            [
                'id'                     => 4,
                'company_name'           => 'Kigali Heights Construction Ltd',
                'company_email'          => 'jobs@kigaliheights.rw',
                'company_phone'          => '+250788300000',
                'company_logo'           => 'companies/kigali-heights-logo.png',
                'company_website'        => null,
                'title'                  => 'Civil Engineer — Structural Assessment Specialist',
                'slug'                   => 'civil-engineer-structural-kigali-heights',
                'description'            => 'We are hiring a Civil Engineer specializing in structural assessment for our ongoing residential projects in Kigali. The role involves inspecting building structures, ensuring compliance with Rwanda Building Code, and providing technical reports.',
                'requirements'           => 'Degree in Civil Engineering, 5+ years structural experience, RHA registration, knowledge of RBC standards.',
                'benefits'               => 'Competitive salary, project bonuses, health insurance, training opportunities.',
                'location'               => 'Kigali, Rwanda',
                'job_type'               => 'full-time',
                'category'               => 'Civil Engineering',
                'salary_min'             => 1200000,
                'salary_max'             => 2000000,
                'salary_currency'        => 'RWF',
                'show_salary'            => 0,
                'application_deadline'   => '2026-08-20',
                'application_email'      => 'jobs@kigaliheights.rw',
                'application_url'        => null,
                'listing_package_id'     => 1,
                'days_purchased'         => 30,
                'views_count'            => 178,
                'unique_views_count'     => 145,
                'total_amount'           => 15000,
                'agent_commission_amount'=> 2250,
                'terra_share_amount'     => 12750,
                'payment_status'         => 'paid',
                'payment_reference'      => 'MTN20260712004',
                'payment_method'         => 'momo',
                'paid_at'                => now()->subDays(17),
                'status'                 => 'active',
                'published_at'           => now()->subDays(17),
                'expires_at'             => now()->addDays(13),
                'rejection_reason'       => null,
                'user_id'                => 2,
                'created_at'             => now()->subDays(18),
                'updated_at'             => now(),
            ],
            [
                'id'                     => 5,
                'company_name'           => 'Lakeview Properties Ltd',
                'company_email'          => 'hr@lakeviewproperties.rw',
                'company_phone'          => '+250788222333',
                'company_logo'           => 'companies/lakeview-properties-logo.png',
                'company_website'        => 'https://www.lakeviewproperties.rw',
                'title'                  => 'Property Marketing Intern — 6-Month Program',
                'slug'                   => 'property-marketing-intern-lakeview-properties',
                'description'            => 'Lakeview Properties Ltd is offering a 6-month internship for a Property Marketing Intern to assist with our digital marketing efforts for lakefront properties in Rubavu and Rusizi. You will gain hands-on experience with Terra Rwanda\'s platform and learn property marketing strategies.',
                'requirements'           => 'Recent graduate in Marketing, Communications, or Business, basic knowledge of social media marketing, fluent in Kinyarwanda and English, interest in real estate.',
                'benefits'               => 'Monthly stipend of 200,000 RWF, mentorship, potential for full-time employment, networking opportunities.',
                'location'               => 'Rubavu, Western Province, Rwanda',
                'job_type'               => 'internship',
                'category'               => 'Marketing',
                'salary_min'             => 200000,
                'salary_max'             => 200000,
                'salary_currency'        => 'RWF',
                'show_salary'            => 1,
                'application_deadline'   => '2026-08-10',
                'application_email'      => 'hr@lakeviewproperties.rw',
                'application_url'        => null,
                'listing_package_id'     => 1,
                'days_purchased'         => 30,
                'views_count'            => 456,
                'unique_views_count'     => 378,
                'total_amount'           => 15000,
                'agent_commission_amount'=> 2250,
                'terra_share_amount'     => 12750,
                'payment_status'         => 'paid',
                'payment_reference'      => 'MTN20260715005',
                'payment_method'         => 'momo',
                'paid_at'                => now()->subDays(14),
                'status'                 => 'active',
                'published_at'           => now()->subDays(14),
                'expires_at'             => now()->addDays(16),
                'rejection_reason'       => null,
                'user_id'                => 5,
                'created_at'             => now()->subDays(15),
                'updated_at'             => now(),
            ],
        ]);
    }
}