<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LandSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('lands')->insert([
            [
                'id'                        => 1,
                'views_count'               => 678,
                'unique_views_count'        => 543,
                'user_id'                   => 5,
                'agent_id'                  => 2,
                'added_by'                  => 5,
                'listing_package_id'        => 4,
                'listing_days'              => 60,
                'listing_fee_total'         => 48000.00,
                'agent_listing_commission'  => 9600.00,
                'terra_listing_revenue'     => 38400.00,
                'owner_name'                => 'Jean-Bosco Niyonsaba',
                'owner_email'               => 'jbosco@gmail.com',
                'owner_phone'               => '+250788111222',
                'owner_id_number'           => '1199780001234567',
                'title'                     => 'Prime Residential Plot in Nyagatovu — Kimironko, Gasabo',
                'description'               => 'Excellent residential plot in the fast-developing Nyagatovu area of Kimironko. Flat terrain with R1 zoning, ideal for a family home or small apartment building. All infrastructure (water, electricity, tarmac road) available. UPI verified and title deed ready for immediate transfer. Just 15 minutes from Kigali CBD.',
                'price'                     => 25000000.00,
                'size_sqm'                  => 600.00,
                'zoning'                    => 'R1',
                'land_use'                  => 'Residential',
                'province'                  => 'Kigali City',
                'district'                  => 'Gasabo',
                'sector'                    => 'Kimironko',
                'cell'                      => 'Nyagatovu',
                'village'                   => 'Kabarore',
                'upi'                       => '1/02/04/006/021',
                'title_doc'                 => 'land/titles/upi-1-02-04-006-021.pdf',
                'is_title_verified'         => 1,
                'status'                    => 'available',
                'negotiable'                => 'negotiable',
                'is_approved'               => 1,
                'expires_at'                => now()->addDays(60),
                'condition'                 => 'for_sale',
                'video_url'                 => 'https://youtube.com/watch?v=nyagatovu-plot-terra',
                'latitude'                  => -1.9235000,
                'longitude'                 => 30.1025000,
                'currency'                  => 'RWF',
                'client_id'                 => 1,
                'service_id'                => 1,
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 2,
                'views_count'               => 445,
                'unique_views_count'        => 378,
                'user_id'                   => 2,
                'agent_id'                  => 1,
                'added_by'                  => 2,
                'listing_package_id'        => 4,
                'listing_days'              => 60,
                'listing_fee_total'         => 48000.00,
                'agent_listing_commission'  => 9600.00,
                'terra_listing_revenue'     => 38400.00,
                'owner_name'                => 'Urwego Development Corporation',
                'owner_email'               => 'info@urwego.rw',
                'owner_phone'               => '+250788444555',
                'owner_id_number'           => null,
                'title'                     => 'Commercial Plot on KN 3 Road — Nyarugenge CBD',
                'description'               => 'Premium commercial plot on the main KN 3 Road in Kigali CBD. R3 zoning allows for high-rise commercial development. Exceptional investment opportunity in the heart of Kigali. Adjacent to major banks and government offices. All utilities connected. Feasibility study available upon request.',
                'price'                     => 500000000.00,
                'size_sqm'                  => 1200.00,
                'zoning'                    => 'Commercial',
                'land_use'                  => 'Commercial',
                'province'                  => 'Kigali City',
                'district'                  => 'Nyarugenge',
                'sector'                    => 'Nyarugenge',
                'cell'                      => 'Rwezamenyo',
                'village'                   => 'Kabasanda',
                'upi'                       => '1/01/01/002/001',
                'title_doc'                 => 'land/titles/upi-1-01-01-002-001.pdf',
                'is_title_verified'         => 1,
                'status'                    => 'available',
                'negotiable'                => 'non_negotiable',
                'is_approved'               => 1,
                'expires_at'                => now()->addDays(60),
                'condition'                 => 'for_sale',
                'video_url'                 => null,
                'latitude'                  => -1.9495000,
                'longitude'                 => 30.0585000,
                'currency'                  => 'RWF',
                'client_id'                 => 4,
                'service_id'                => 1,
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 3,
                'views_count'               => 234,
                'unique_views_count'        => 198,
                'user_id'                   => 4,
                'agent_id'                  => 3,
                'added_by'                  => 4,
                'listing_package_id'        => 3,
                'listing_days'              => 30,
                'listing_fee_total'         => 12000.00,
                'agent_listing_commission'  => 1800.00,
                'terra_listing_revenue'     => 10200.00,
                'owner_name'                => 'Dr. Samuel Habarugira',
                'owner_email'               => 'dr.habarugira@gmail.com',
                'owner_phone'               => '+250788333444',
                'owner_id_number'           => '1199750003456789',
                'title'                     => 'Agricultural Land in Tumba — Huye, Southern Province',
                'description'               => 'Fertile agricultural land in Tumba sector, Huye district. Ideal for tea, coffee, or maize farming. The land has gentle slopes with natural irrigation from a nearby stream. Partially developed with a small storage structure. Access road available. Title deed verified and ready for transfer.',
                'price'                     => 8000000.00,
                'size_sqm'                  => 5000.00,
                'zoning'                    => 'Agricultural',
                'land_use'                  => 'Agriculture',
                'province'                  => 'Southern Province',
                'district'                  => 'Huye',
                'sector'                    => 'Tumba',
                'cell'                      => 'Tumba',
                'village'                   => 'Rwaniro',
                'upi'                       => '3/06/08/009/005',
                'title_doc'                 => 'land/titles/upi-3-06-08-009-005.pdf',
                'is_title_verified'         => 1,
                'status'                    => 'available',
                'negotiable'                => 'negotiable',
                'is_approved'               => 1,
                'expires_at'                => now()->addDays(30),
                'condition'                 => 'for_sale',
                'video_url'                 => null,
                'latitude'                  => -2.5767000,
                'longitude'                 => 29.7394000,
                'currency'                  => 'RWF',
                'client_id'                 => 3,
                'service_id'                => 1,
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 4,
                'views_count'               => 567,
                'unique_views_count'        => 456,
                'user_id'                   => 2,
                'agent_id'                  => 5,
                'added_by'                  => 2,
                'listing_package_id'        => 4,
                'listing_days'              => 60,
                'listing_fee_total'         => 48000.00,
                'agent_listing_commission'  => 9600.00,
                'terra_listing_revenue'     => 38400.00,
                'owner_name'                => 'Chantal Mukamana',
                'owner_email'               => 'chantal.m@gmail.com',
                'owner_phone'               => '+250788222333',
                'owner_id_number'           => '1199800002345678',
                'title'                     => 'Lakefront Plot in Rubavu — Stunning Lake Kivu Views',
                'description'               => 'Rare lakefront plot with direct views of Lake Kivu and the Nyiragongo volcano in the Democratic Republic of Congo. R2 zoning allows for a guesthouse, eco-lodge, or luxury residence. All utilities available. Just 10 minutes from Gisenyi town center. An exceptional opportunity for tourism investment in the Western Province.',
                'price'                     => 45000000.00,
                'size_sqm'                  => 800.00,
                'zoning'                    => 'R2',
                'land_use'                  => 'Mixed Residential',
                'province'                  => 'Western Province',
                'district'                  => 'Rubavu',
                'sector'                    => 'Gisenyi',
                'cell'                      => 'Gisenyi',
                'village'                   => 'Rubavu',
                'upi'                       => '5/10/10/010/003',
                'title_doc'                 => 'land/titles/upi-5-10-10-010-003.pdf',
                'is_title_verified'         => 1,
                'status'                    => 'available',
                'negotiable'                => 'negotiable',
                'is_approved'               => 1,
                'expires_at'                => now()->addDays(60),
                'condition'                 => 'for_sale',
                'video_url'                 => 'https://youtube.com/watch?v=rubavu-lakefront-terra',
                'latitude'                  => -1.6837000,
                'longitude'                 => 29.2935000,
                'currency'                  => 'RWF',
                'client_id'                 => 2,
                'service_id'                => 1,
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 5,
                'views_count'               => 312,
                'unique_views_count'        => 267,
                'user_id'                   => 4,
                'agent_id'                  => 2,
                'added_by'                  => 4,
                'listing_package_id'        => 3,
                'listing_days'              => 30,
                'listing_fee_total'         => 12000.00,
                'agent_listing_commission'  => 1800.00,
                'terra_listing_revenue'     => 10200.00,
                'owner_name'                => 'Immaculée Nyirahabimana',
                'owner_email'               => 'immaculee.n@gmail.com',
                'owner_phone'               => '+250788555666',
                'owner_id_number'           => '1199850005678901',
                'title'                     => 'R2 Residential Plot in Nyamata — Bugesera, Near New Airport',
                'description'               => 'Strategic residential plot in Nyamata, Bugesera district, just 5 km from the new Bugesera International Airport. R2 zoning suitable for multi-family residential development. Excellent investment opportunity as the area is rapidly developing with new infrastructure. Tarmac road access, electricity, and water available. Title deed verified.',
                'price'                     => 12000000.00,
                'size_sqm'                  => 900.00,
                'zoning'                    => 'R2',
                'land_use'                  => 'Residential',
                'province'                  => 'Eastern Province',
                'district'                  => 'Bugesera',
                'sector'                    => 'Nyamata',
                'cell'                      => 'Rwamagana',
                'village'                   => 'Mayange',
                'upi'                       => '4/09/012/015/007',
                'title_doc'                 => 'land/titles/upi-4-09-012-015-007.pdf',
                'is_title_verified'         => 1,
                'status'                    => 'available',
                'negotiable'                => 'negotiable',
                'is_approved'               => 1,
                'expires_at'                => now()->addDays(30),
                'condition'                 => 'for_sale',
                'video_url'                 => null,
                'latitude'                  => -2.2075000,
                'longitude'                 => 30.1075000,
                'currency'                  => 'RWF',
                'client_id'                 => 5,
                'service_id'                => 1,
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
        ]);
    }
}