<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ListingSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('listings')->insert([
            [
                'id'                    => 1,
                'user_id'               => 2,
                'agent_id'              => 1,
                'listing_package_id'    => 2,  // House Premium
                'listing_type'          => 'house',
                'package_tier'          => 'premium',
                'title'                 => 'Premium House Listing — Kacyiru Villa',
                'description'           => '60-day premium listing for the 4-bedroom villa in Kacyiru with featured placement and video.',
                'start_date'            => now()->subDays(14)->format('Y-m-d'),
                'end_date'              => now()->addDays(46)->format('Y-m-d'),
                'duration_days'         => 60,
                'base_price_per_day'    => 1000,
                'gross_amount'          => 60000,
                'duration_discount_pct' => 0.00,
                'discount_amount'       => 0,
                'net_amount'            => 60000,
                'status'                => 'active',
                'payment_status'        => 'paid',
                'paid_at'               => now()->subDays(14),
                'meta'                  => json_encode(['property_id' => 1, 'property_type' => 'house']),
                'created_at'            => now()->subDays(15),
                'updated_at'            => now(),
            ],
            [
                'id'                    => 2,
                'user_id'               => 5,
                'agent_id'              => 2,
                'listing_package_id'    => 4,  // Land Premium
                'listing_type'          => 'land',
                'package_tier'          => 'premium',
                'title'                 => 'Premium Land Listing — Nyagatovu Plot',
                'description'           => '60-day premium listing for the residential plot in Nyagatovu.',
                'start_date'            => now()->subDays(10)->format('Y-m-d'),
                'end_date'              => now()->addDays(50)->format('Y-m-d'),
                'duration_days'         => 60,
                'base_price_per_day'    => 800,
                'gross_amount'          => 48000,
                'duration_discount_pct' => 0.00,
                'discount_amount'       => 0,
                'net_amount'            => 48000,
                'status'                => 'active',
                'payment_status'        => 'paid',
                'paid_at'               => now()->subDays(10),
                'meta'                  => json_encode(['property_id' => 1, 'property_type' => 'land']),
                'created_at'            => now()->subDays(12),
                'updated_at'            => now(),
            ],
            [
                'id'                    => 3,
                'user_id'               => 2,
                'agent_id'              => 4,
                'listing_package_id'    => 2,  // House Premium
                'listing_type'          => 'house',
                'package_tier'          => 'premium',
                'title'                 => 'Premium House Listing — Kimihurura Penthouse',
                'description'           => '60-day premium listing for the luxury penthouse in Kimihurura.',
                'start_date'            => now()->subDays(20)->format('Y-m-d'),
                'end_date'              => now()->addDays(40)->format('Y-m-d'),
                'duration_days'         => 60,
                'base_price_per_day'    => 1000,
                'gross_amount'          => 60000,
                'duration_discount_pct' => 0.00,
                'discount_amount'       => 0,
                'net_amount'            => 60000,
                'status'                => 'active',
                'payment_status'        => 'paid',
                'paid_at'               => now()->subDays(20),
                'meta'                  => json_encode(['property_id' => 3, 'property_type' => 'house']),
                'created_at'            => now()->subDays(22),
                'updated_at'            => now(),
            ],
            [
                'id'                    => 4,
                'user_id'               => 2,
                'agent_id'              => 5,
                'listing_package_id'    => 4,  // Land Premium
                'listing_type'          => 'land',
                'package_tier'          => 'premium',
                'title'                 => 'Premium Land Listing — Rubavu Lakefront',
                'description'           => '60-day premium listing for the lakefront plot in Rubavu.',
                'start_date'            => now()->subDays(8)->format('Y-m-d'),
                'end_date'              => now()->addDays(52)->format('Y-m-d'),
                'duration_days'         => 60,
                'base_price_per_day'    => 800,
                'gross_amount'          => 48000,
                'duration_discount_pct' => 0.00,
                'discount_amount'       => 0,
                'net_amount'            => 48000,
                'status'                => 'active',
                'payment_status'        => 'paid',
                'paid_at'               => now()->subDays(8),
                'meta'                  => json_encode(['property_id' => 4, 'property_type' => 'land']),
                'created_at'            => now()->subDays(10),
                'updated_at'            => now(),
            ],
            [
                'id'                    => 5,
                'user_id'               => 3,
                'agent_id'              => 1,
                'listing_package_id'    => 5,  // Architectural Design Standard
                'listing_type'          => 'architectural_design',
                'package_tier'          => 'standard',
                'title'                 => 'Standard Design Listing — 3-Bedroom Bungalow Kigali Style',
                'description'           => '30-day standard listing for the 3-bedroom bungalow architectural design.',
                'start_date'            => now()->subDays(5)->format('Y-m-d'),
                'end_date'              => now()->addDays(25)->format('Y-m-d'),
                'duration_days'         => 30,
                'base_price_per_day'    => 300,
                'gross_amount'          => 9000,
                'duration_discount_pct' => 0.00,
                'discount_amount'       => 0,
                'net_amount'            => 9000,
                'status'                => 'active',
                'payment_status'        => 'paid',
                'paid_at'               => now()->subDays(5),
                'meta'                  => json_encode(['property_id' => 1, 'property_type' => 'architectural_design']),
                'created_at'            => now()->subDays(6),
                'updated_at'            => now(),
            ],
        ]);
    }
}