<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ListingPaymentSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('listing_payments')->insert([
            [
                'id'                 => 1,
                'payable_type'       => 'App\\Models\\House',
                'payable_id'         => 1,
                'user_id'            => 2,
                'payment_purpose'    => 'listing_fee',
                'amount'             => 60000.00,
                'currency'           => 'RWF',
                'payment_method'     => 'momo',
                'phone_number'       => '+250788234567',
                'gateway_reference'  => 'MTN20260715001',
                'transaction_id'     => 'TRX-' . strtoupper(Str::random(10)),
                'gateway_response'   => json_encode(['status' => 'SUCCESS', 'message' => 'Payment completed']),
                'reference'          => 'PAY-' . strtoupper(Str::random(8)),
                'status'             => 'completed',
                'paid_at'            => now()->subDays(14),
                'failure_reason'     => null,
                'created_at'         => now()->subDays(15),
                'updated_at'         => now(),
            ],
            [
                'id'                 => 2,
                'payable_type'       => 'App\\Models\\Land',
                'payable_id'         => 1,
                'user_id'            => 5,
                'payment_purpose'    => 'listing_fee',
                'amount'             => 48000.00,
                'currency'           => 'RWF',
                'payment_method'     => 'momo',
                'phone_number'       => '+250788567890',
                'gateway_reference'  => 'MTN20260720002',
                'transaction_id'     => 'TRX-' . strtoupper(Str::random(10)),
                'gateway_response'   => json_encode(['status' => 'SUCCESS', 'message' => 'Payment completed']),
                'reference'          => 'PAY-' . strtoupper(Str::random(8)),
                'status'             => 'completed',
                'paid_at'            => now()->subDays(10),
                'failure_reason'     => null,
                'created_at'         => now()->subDays(12),
                'updated_at'         => now(),
            ],
            [
                'id'                 => 3,
                'payable_type'       => 'App\\Models\\House',
                'payable_id'         => 3,
                'user_id'            => 2,
                'payment_purpose'    => 'listing_fee',
                'amount'             => 60000.00,
                'currency'           => 'RWF',
                'payment_method'     => 'momo',
                'phone_number'       => '+250788234567',
                'gateway_reference'  => 'MTN20260709003',
                'transaction_id'     => 'TRX-' . strtoupper(Str::random(10)),
                'gateway_response'   => json_encode(['status' => 'SUCCESS', 'message' => 'Payment completed']),
                'reference'          => 'PAY-' . strtoupper(Str::random(8)),
                'status'             => 'completed',
                'paid_at'            => now()->subDays(20),
                'failure_reason'     => null,
                'created_at'         => now()->subDays(22),
                'updated_at'         => now(),
            ],
            [
                'id'                 => 4,
                'payable_type'       => 'App\\Models\\Land',
                'payable_id'         => 4,
                'user_id'            => 2,
                'payment_purpose'    => 'listing_fee',
                'amount'             => 48000.00,
                'currency'           => 'RWF',
                'payment_method'     => 'momo',
                'phone_number'       => '+250788234567',
                'gateway_reference'  => 'MTN20260719004',
                'transaction_id'     => 'TRX-' . strtoupper(Str::random(10)),
                'gateway_response'   => json_encode(['status' => 'SUCCESS', 'message' => 'Payment completed']),
                'reference'          => 'PAY-' . strtoupper(Str::random(8)),
                'status'             => 'completed',
                'paid_at'            => now()->subDays(8),
                'failure_reason'     => null,
                'created_at'         => now()->subDays(10),
                'updated_at'         => now(),
            ],
            [
                'id'                 => 5,
                'payable_type'       => 'App\\Models\\ArchitecturalDesign',
                'payable_id'         => 1,
                'user_id'            => 3,
                'payment_purpose'    => 'listing_fee',
                'amount'             => 9000.00,
                'currency'           => 'RWF',
                'payment_method'     => 'momo',
                'phone_number'       => '+250788345678',
                'gateway_reference'  => 'MTN20260724005',
                'transaction_id'     => 'TRX-' . strtoupper(Str::random(10)),
                'gateway_response'   => json_encode(['status' => 'SUCCESS', 'message' => 'Payment completed']),
                'reference'          => 'PAY-' . strtoupper(Str::random(8)),
                'status'             => 'completed',
                'paid_at'            => now()->subDays(5),
                'failure_reason'     => null,
                'created_at'         => now()->subDays(6),
                'updated_at'         => now(),
            ],
        ]);
    }
}